### PR TITLE
Coherent licensing

### PR DESCRIPTION
**Pull request by Michael-A-Heuer**
## Description
The licensing of the contracts should be coherent.

## Type of change

- license change

## Checklist:

- [x] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

### CODE REVIEW

**Comment by novaknole** [comment]
LGTM

**Comment by Michael-A-Heuer** [comment]
I opened this draft with the expectation that we need to change licenses in some contracts.

**Review by brickpop — APPROVED** [review]

**Review by Rekard0 — APPROVED** [review]
LGTM

**Comment by Michael-A-Heuer** [comment]
This will be done as part of a later PR

**Pull request closed without merging**
